# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accountNumber', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=50)),
                ('balance', models.FloatField(default=0.0)),
                ('accountType', models.CharField(max_length=30)),
                ('interestRate', models.FloatField(blank=True, default=0.0)),
                ('routingNumber', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('accountNumber', models.CharField(max_length=50)),
                ('routingNumber', models.CharField(max_length=50)),
                ('accountType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fromAccountNumber', models.CharField(max_length=50)),
                ('toAccountNumber', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('pending', models.BooleanField(default=True)),
                ('amount', models.FloatField(default=0.0)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
