# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('loan_type', models.CharField(default='', max_length=100)),
                ('start_balance', models.FloatField()),
                ('current_balance', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('monthly_payment', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_interval', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('loan_id',),
            },
        ),
    ]
