import uuid
from dateutil import parser


def init_data(apps, schema_editor):
    Account = apps.get_model("authentication", "Account")
    db_alias = schema_editor.connection.alias
    Account.objects.using(db_alias).bulk_create([
        Account(id=uuid.uuid4(), email="team8best@gmail.com", first_name="Team", last_name="Best",
                dob=parser.parse('11/11/2017'), primary_phone_number="412-123-6666",
                alternative_phone_number="", home_address_1="5000 Forbes Ave", home_address_2="Apt#123",
                home_address_city="Pittsburgh", home_address_state="PA", home_address_country="US",
                home_address_zip="15213", mail_address_1="5000 Forbes Ave", mail_address_2="Apt#123",
                mail_address_city="Pittsburgh", mail_address_state="PA", mail_address_country="US",
                mail_address_zip="15213", license_number="88-666-123", license_type="Driver License",
                license_issue_date=parser.parse("11/12/2017"),
                license_expire=parser.parse("11/12/2018"),
                license_geo="PA", occupation="CEO", annual_income=100000, employee="Carneige Mellon University",
                security_question_1=2, security_answer_1="Unknown", security_question_2=4, security_answer_2="Unknown",
                security_question_3=1, security_answer_3="Unknown", language='E', pin_code='CMU6661234',
                registration_status=False),
        Account(id=uuid.uuid4(), email="haha@gmail.com", first_name="Ha", last_name="Ha",
                dob=parser.parse('11/11/1991'), primary_phone_number="111-111-1111",
                alternative_phone_number="", home_address_1="111 Haha Ave", home_address_2="",
                home_address_city="Columbus", home_address_state="OH", home_address_country="US",
                home_address_zip="43210", mail_address_1="111 Haha Ave", mail_address_2="",
                mail_address_city="Columbus", mail_address_state="OH", mail_address_country="US",
                mail_address_zip="43210", license_number="11-111-111", license_type="Driver License",
                license_issue_date=parser.parse("11/11/1997"),
                license_expire=parser.parse("11/11/2000"),
                license_geo="OH", occupation="CFO", annual_income=1000000000, employee="Deloitte",
                security_question_1=2, security_answer_1="Unknown", security_question_2=4, security_answer_2="Unknown",
                security_question_3=1, security_answer_3="Unknown", language='E', pin_code='CMU11111111',
                registration_status=False),
        Account(id=uuid.uuid4(), email="hello@gmail.com", first_name="Hello", last_name="World",
                dob=parser.parse('11/11/1995'), primary_phone_number="897-678-8768",
                alternative_phone_number="", home_address_1="4578 Murray Ave", home_address_2="Apt#456",
                home_address_city="Pittsburgh", home_address_state="PA", home_address_country="US",
                home_address_zip="15217", mail_address_1="4578 Murray Ave", mail_address_2="Apt#456",
                mail_address_city="Pittsburgh", mail_address_state="PA", mail_address_country="US",
                mail_address_zip="15217", license_number="22-222-222", license_type="Driver License",
                license_issue_date=parser.parse("11/12/2013"),
                license_expire=parser.parse("11/12/2014"),
                license_geo="PA", occupation="CTO", annual_income=10000000, employee="Carneige Mellon University",
                security_question_1=2, security_answer_1="Unknown", security_question_2=4, security_answer_2="Unknown",
                security_question_3=1, security_answer_3="Unknown", language='S', pin_code='CMU1233214',
                registration_status=False),
        Account(id=uuid.uuid4(), email="shuai@gmail.com", first_name="Haoshuai", last_name="Qin",
                dob=parser.parse('11/11/1990'), primary_phone_number="412-888-2393",
                alternative_phone_number="", home_address_1="888 Handsome Road", home_address_2="Apt#888",
                home_address_city="Pittsburgh", home_address_state="PA", home_address_country="US",
                home_address_zip="15218", mail_address_1="888 Handsome Road", mail_address_2="Apt#888",
                mail_address_city="Pittsburgh", mail_address_state="PA", mail_address_country="US",
                mail_address_zip="15218", license_number="88-888-888", license_type="Driver License",
                license_issue_date=parser.parse("11/12/2015"),
                license_expire=parser.parse("11/12/2019"),
                license_geo="PA", occupation="CEO", annual_income=888888888, employee="Google",
                security_question_1=2, security_answer_1="Unknown", security_question_2=4, security_answer_2="Unknown",
                security_question_3=1, security_answer_3="Unknown", language='E', pin_code='CMU1288392',
                registration_status=False),
        Account(id=uuid.uuid4(), email="andrewmoore@cmu.edu", first_name="Andrew", last_name="Moore",
                dob=parser.parse('11/11/1980'), primary_phone_number="412-454-5634",
                alternative_phone_number="", home_address_1="123 What Ave", home_address_2="",
                home_address_city="Pittsburgh", home_address_state="PA", home_address_country="US",
                home_address_zip="15216", mail_address_1="123 What Ave", mail_address_2="",
                mail_address_city="Pittsburgh", mail_address_state="PA", mail_address_country="US",
                mail_address_zip="15216", license_number="12-345-678", license_type="Driver License",
                license_issue_date=parser.parse("11/25/2017"),
                license_expire=parser.parse("11/25/2019"),
                license_geo="PA", occupation="Machine Learning Head", annual_income=100000000,
                employee="Carneige Mellon University",
                security_question_1=1, security_answer_1="Unknown", security_question_2=2, security_answer_2="Unknown",
                security_question_3=4, security_answer_3="Unknown", language='S', pin_code='CMU1521366',
                registration_status=False),
        Account(id=uuid.uuid4(), email="ali@gmail.com", first_name="Ali", last_name="Lee",
                dob=parser.parse('01/02/1999'), primary_phone_number="123-222-3333",
                alternative_phone_number="", home_address_1="312 Fifth Ave", home_address_2="Apt#102",
                home_address_city="Pittsburgh", home_address_state="PA", home_address_country="US",
                home_address_zip="15213", mail_address_1="312 Fifth Ave", mail_address_2="Apt#102",
                mail_address_city="Pittsburgh", mail_address_state="PA", mail_address_country="US",
                mail_address_zip="15213", license_number="22-111-333", license_type="Driver License",
                license_issue_date=parser.parse("12/22/2016"),
                license_expire=parser.parse("12/20/2021"),
                license_geo="PA", occupation="Analyst", annual_income=70000, employee="Apple",
                security_question_1=2, security_answer_1="Unknown", security_question_2=3,
                security_answer_2="Hard to say",
                security_question_3=1, security_answer_3="Unknown", language='E', pin_code='CMU3211234',
                registration_status=False),
    ])
